version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../:/workspace:cached

    command: sleep infinity

    networks:
      - internal_network
      - external_network
networks:
  internal_network:
    internal: true
  external_network: